### ISSUE TITLE
App force close when adding an account

### ISSUE THREAD

**Issue by 4e4c52** [4e4c52/mt-AccountCenter#1]
When adding an account, the app force close but the account is saved.
Debug log:

```
java.lang.ClassCastException: android.app.AlertDialog
at com.syrinxoon.mtaccountcenter.AddAccountActivity$8.run(AddAccountActivity.java:232)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by jstart** [comment]
any updates on fixing this one?  Are you still working on this at all?  Has the (mt) API Added any more features?

**Comment by 4e4c52** [comment]
It was occurring randomly. I've not worked on the app since the creation of this repo.
About the API, it hasn't mode since, they were supposed to be working on new features but nothing for now.

**Comment by jstart** [comment]
Cool, just wanted to check on whatever happened with this project.  Are you seeing any significant number of downloads?  I was thinking of maybe trying to improve the UI, but I wouldn't if no one is using it.

**Comment by 4e4c52** [comment]
Here are the current stats:

![Stats preview](http://d3j5vwomefv46c.cloudfront.net/photos/full/580806025.png?key=95493&Expires=1337201111&Key-Pair-Id=APKAIYVGSUJFNRFZBBTA&Signature=np2jRLr1tlKUmo-ATZARJFHC8E6X0iTQkuZu44ONBcbu2t1APQVuvA8rc5tFCTGMEMewXcJyV6gvLUUkgnAv6IKAyr0JIULRi4uLzcLkwjru9G~0RAZZBzmxlWLnTAXnoeh~dEehXbpByKFANLTw5lYqvP-fAw6BmkmD7MCdkGU_)

And

![Detailed stats](http://d3j5vwomefv46c.cloudfront.net/photos/large/580805904.png?key=974920&Expires=1337201127&Key-Pair-Id=APKAIYVGSUJFNRFZBBTA&Signature=0stwRhajv4qMta0IeNbUCAsr5-A6kO~O4962tLkCoiUR1IdPdffy~JM4dti~E6KUzYdlvCwEvAzj9fp-l~07zb~uoKK-7w-tiqyDv4hDbM9EiokjgwSCK7QW5LOm0TGO7KdE7Hnu68W-SLcPoV7mSo1a66LWGQUAYek0ULrdcCQ_)

If you want to improve the UI, go for it ;-)

**Comment by jstart** [comment]
Those image stats links don't work, but I might clean up the UI anyway :P

**Comment by 4e4c52** [comment]
They're on my Twitpic profile ;-)
On May 17, 2012 1:48 AM, "Christopher" <
reply@reply.github.com>
wrote:
